### ISSUE TITLE
VMD crashes if bonds are specified in the H5MD file

### ISSUE THREAD

**Issue by Lun4m** [Cascella-Group-UiO/HyMD#104]
I can't figure out what the exact problem is, but I think (?) it has to do with the following lines.
Honestly these lines look fine to me, but If I comment them out then I can visualize the simulation (without bonds).
https://github.com/Cascella-Group-UiO/HyMD-2021/blob/49123d018059b54e7ecbc1930939bf6f63aa57b0/hymd/file_io.py#L272-L288

Here's also a screenshot from my terminal:

![Screenshot from 2021-05-26 15-02-14](https://user-images.githubusercontent.com/15078179/119665387-a3c36300-be34-11eb-9eee-4f1d8ddee4d8.png)

Maybe my VMD-H5MD plugin wasn't compiled properly/some libraries weren't linked properly, but I can see the bonds if I `vmd` the sample files provided in the plugin repo.
Anyway you can see that the plugin reads 15 bonds, but VMD gives out only 13.

**Comment by mortele** [comment]
Reasonably sure this is because of #133

**Comment by Lun4m** [comment]
@mortele Note that writing bonds info to the output h5 is commented out in `file_io.py` since the cbt merge.

**Comment by mortele** [comment]
*May* be fixed now after fc03aee91d6cf952639d16767fa849b6fba4cecc

**Comment by mortele** [comment]
Can you check if this works with the new version when you get a chance @Lun4m ? I never had a problem with it, even when the bonds were wrongly defined, so hard for me to reproduce this error.

**Comment by Lun4m** [comment]
Yep, I can confirm it's fixed now!
