### ISSUE TITLE
Random lipids misplaced in specific frames

### ISSUE THREAD

**Issue by samiransen23** [Cascella-Group-UiO/HyMD#108]
Across an NPT trajectory of dppc, some random lipid (all/some of 12 beads) goes to the origin (0,0,0)  in specific frames that are randomly placed. Frame 32, 35, 39, 42, etc.
This problem can be seen in the density profile AND in vmd visualisation.
<img align="left" src="https://user-images.githubusercontent.com/59645138/119996205-bf627100-bfce-11eb-9cee-be2a7993dc02.png" width="40%" height="40%">
<img align="right" src="https://user-images.githubusercontent.com/59645138/119996486-1b2cfa00-bfcf-11eb-988f-05654d96ef4d.png" width="50%" height="50%">

**Comment by mortele** [comment]
Did we ever figure out the problem underlying this issue @samiransen23 ? 🤔

**Comment by samiransen23** [comment]
@mortele : Oh, ya. This had to do with the residues left behind when the box was being altered. Redoing just `pm.decompose` was not enough. It's fixed now. Sorry forgot to close this
