### ISSUE TITLE
VMD plugin labelling problem

### ISSUE THREAD

**Issue by samiransen23** [Cascella-Group-UiO/HyMD#109]
One lipid may be selected by the `residue` keyword.  
`residue 0` = First lipid in `sim.h5`  
One lipid may also be selected by the `index` keyword.  
`index 0 to 11` = First lipid in `sim.h5`  

While `index` selects the correct beads, `residue` makes an incorrect counting and shows the last bead of the previous lipid.  

![image](https://user-images.githubusercontent.com/59645138/119997200-c5a51d00-bfcf-11eb-8c2f-b17e2aee05d7.png)

**Comment by mortele** [comment]
This *should* be fixed now after fc03aee91d6cf952639d16767fa849b6fba4cecc .

https://github.com/Cascella-Group-UiO/HyMD/blob/fc03aee91d6cf952639d16767fa849b6fba4cecc/hymd/file_io.py#L309

**Comment by Lun4m** [comment]
I can confirm this is fixed as well!
