### ISSUE TITLE
Numpy seed not set correctly

### ISSUE THREAD

**Issue by samiransen23** [Cascella-Group-UiO/HyMD#110]
`main.py:` 
```python
    if args.seed is not None:
        np.random.seed(args.seed)
```

`thermostat.py:`
`numpy` is imported again. Seed information is not retained.

**Comment by hmcezar** [comment]
I've been looking at some older issues and this one still seems relevant.

A couple of links that can be useful while addressing it:
- https://albertcthomas.github.io/good-practices-random-number-generators/
- https://numpy.org/doc/stable/reference/random/parallel.html

I'm assigning this to myself.
