### ISSUE TITLE
prepare_bonds_old bug

### ISSUE THREAD

**Issue by Lun4m** [Cascella-Group-UiO/HyMD#115]
https://github.com/Cascella-Group-UiO/HyMD-2021/blob/49123d018059b54e7ecbc1930939bf6f63aa57b0/hymd/force.py#L65-L66

These lines are the same.

**Comment by mortele** [comment]
This is officially fixed now in the v1.0.0 release of e411b906f1adfca24e09b5e1ac7fcdcf428f1553
