### ISSUE TITLE
Utils folder is messy

### ISSUE THREAD

**Issue by Lun4m** [Cascella-Group-UiO/HyMD#141]
Most of the scripts are not well documented and some are not needed at all.

**Comment by mortele** [comment]
Did we clean this thoroughly enough with #140 and #169 @Lun4m ? Can we safely close this?

**Comment by Lun4m** [comment]
I think the scripts are readable and well commented (since you wrote them :sweat_smile:), maybe it could be useful to separate them in subcategories, like system preparation/file conversion, parameter optimization, analysis, etc. but it can be done later. 
So I'll close this for now.
