### ISSUE TITLE
Add setting to disable PBC

### ISSUE THREAD

**Issue by Lun4m** [Cascella-Group-UiO/HyMD#155]
It would be nice to be able to selectively disable PBC

**Comment by mortele** [comment]
As in; write unwrapped particle trajectories to file? If you want to *actually* not have PBC active, I guess we could implement hard simulation box walls. Pretty sure it would be straightforward to change with the pmesh implementation, we probably just need to change the k vector from cyclic to one of the other alternatives.

**Comment by Lun4m** [comment]
No, I was thinking about simulation of solid surfaces. But I guess in that case you don't actually need to turn PBC off, you just need to "freeze" the atoms in the solid phase. So I'll close this for now!
