### ISSUE TITLE
Documentation badge

### ISSUE THREAD

**Issue by yhtang** [Cascella-Group-UiO/HyMD#158]
Another question related to the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4149):

The documentation badge currently points to this repo's Actions page. Perhaps changing it to the actual online docs page would be more useful for potential users?

**Comment by mortele** [comment]
Hi @yhtang, thank you for pointing this out. I agree that it would be much more useful for this link to point to the actual documentation.

**Comment by mortele** [comment]
Changed in d249209c9a4902e0184433ad544687cf6cf38133.
