### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by yhtang** [Cascella-Group-UiO/HyMD#159]
Hi Morten,

Another question here regarding the [JOSS review](https://github.com/openjournals/joss-reviews/issues/4149). It seems like the online documentation page does not include a page on guidelines for community contributions. Specifically, this pertains to the question:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Could you please point me to this page if I happened to miss it, or maybe add something along the line if it does not exist yet? Thanks!

**Comment by mortele** [comment]
Hi @yhtang, thanks for pointing this out. Right now we have not defined any such guidelines, but we enthusiastically encourage and welcome any contributions from external contributors as will get to this ASAP.

**Comment by yhtang** [comment]
Got it. Thanks for the update. 😁

**Comment by mortele** [comment]
Just linking #163 here for reference.
