### ISSUE TITLE
Supplemental instructions to install MPI compiler

### ISSUE THREAD

**Issue by blakeaw** [Cascella-Group-UiO/HyMD#161]
Hi,

This issue is part of the JOSS Review at https://github.com/openjournals/joss-reviews/issues/4149

Since a MPI compiler is required for installation it might be good to include supplemental instructions for installing the compiler in case users don't already have one installed on their system.  For example, I installed hymd in a WSL2 Ubuntu 20.04 instance which didn't have MPI compilers already. I ended up using the following for mpich:
```
sudo apt install mpich libmpich-dev
``` 
And then installing mpi4py:
```
CC=mpicc pip install mpi4py
```

This comment may have some overlap with Issue https://github.com/Cascella-Group-UiO/HyMD/issues/157.

**Comment by blakeaw** [comment]
Ok, I see. Thanks!
I do think maybe explicit is still better here since the mpi-enabled hdf5 dependency is listed as optional. If you follow the pip install instructions that are listed first without doing the mpi-enabled hdf5 step (as I did initially) but you don't already have the mpi compiler the install will fail when it tries to build mpi4py. 

I'd also maybe recommend listing the dependencies first by moving the __Install dependencies__ subsection to the front of the **Installation** section of the README (and similarly in the documentation). That way users see the dependencies (in particular, the non-python ones) and can make sure they are installed first before they try to install hymd itself.  Also, if you rearrange you could probably move this line `python3 -m pip install --upgrade numpy mpi4py cython` into the dependencies section (and note that those are core dependencies).

**Comment by mortele** [comment]
Hi again @blakeaw, #172 updates and rearranges the installation instructions to explicitly include installing an MPI-enabled C compiler. Also, the dependencies are moved further up, making the whole presentation more sane. 

Think this issue can be safely closed now.

**Comment by blakeaw** [comment]
Hi @mortele, it looks good. Thanks. I'll go ahead and close. 

Just as a side note,  as the warning in installation docs suggested I couldn't get mpi-enabled h5py to install with python 3.10. But there weren't any problems installing in a new conda environment with python 3.8.
