### ISSUE TITLE
exec() cannot modify local variables

### ISSUE THREAD

**Issue by hmcezar** [Cascella-Group-UiO/HyMD#174]
In `main.py` the `_cmd_receive_dd ` string is used to unpack the return values of `domain_decomposition`.
However, all the variables (`positions`, `velocities`, `indices`, etc) are local to the `main()` function and, therefore, cannot be modified within the `exec()` command.

More about this in: https://stackoverflow.com/a/45535337/3254658

I'm not sure of the impact of this on performance or results.

Maybe a solution would be to pass a locals dictionary to `exec()` and retrieve the values from there after the command.

**Comment by hmcezar** [comment]
It's uglier, I know, but a solution would be to return unpacking directly to the variables, like

```python
        (positions,
        velocities,
        indices,
        bond_forces,
        angle_forces,
        dihedral_forces,
        reconstructed_forces,
        field_forces,
        names,
        types,
        *optional) = domain_decomposition(
            positions,
            pm,
            *tuple(args_in),
            molecules=molecules if molecules_flag else None,
            bonds=bonds if molecules_flag else None,
            verbose=args.verbose,
            comm=comm,
        )

        if charges_flag:
            charges = optional.pop(0)
            elec_forces = optional.pop(0)
        if molecules_flag:
            bonds = optional.pop(0)
            molecules = optional.pop(0)
```

**Comment by mortele** [comment]
> It's uglier, I know, but a solution would be to return unpacking directly to the variables, like
> 
> ```python
>         (positions,
>         velocities,
>         indices,
>         bond_forces,
>         angle_forces,
>         dihedral_forces,
>         reconstructed_forces,
>         field_forces,
>         names,
>         types,
>         *optional) = domain_decomposition(
>             positions,
>             pm,
>             *tuple(args_in),
>             molecules=molecules if molecules_flag else None,
>             bonds=bonds if molecules_flag else None,
>             verbose=args.verbose,
>             comm=comm,
>         )
> 
>         if charges_flag:
>             charges = optional.pop(0)
>             elec_forces = optional.pop(0)
>         if molecules_flag:
>             bonds = optional.pop(0)
>             molecules = optional.pop(0)
> ```

We used to do this, but it ends up being a giant pain to manage. If we can make this more stream-lined in some way I am all for it. 👍🏻
