### ISSUE TITLE
Time is zero after first force computation

### ISSUE THREAD

**Issue by hmcezar** [Cascella-Group-UiO/HyMD#177]
Before the main MD loop, we log the information in what is `t=0`, and that is fine.

However, when the main loop starts, we have `step=0`, which means after the first force calculations, we have `t=0` for logging purposes.
This is strange for me, from the velocity verlet scheme we are employing, I'd expect `F=F(dt)` after the first force calculations.
This also raises the `step != 0` [here](https://github.com/Cascella-Group-UiO/HyMD/blob/4414df183f4641c53ad316228d04bade9d91fa1c/hymd/main.py#L729).

Solution would be to change the main loop for `range(1,config.n_steps+1)`.
In the end, we would also have the last print to have the information for step `config.n_steps`, which is what the user requested.

What do you guys think?

**Comment by mortele** [comment]
Yes, this is just a straight up bug. Should be changed to `range (1, config.n_steps + 1)`. 👍
