### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by hmcezar** [Cascella-Group-UiO/HyMD#186]
When running simulations for a lot of steps, it looks like there are memory leaks which make the memory usage increase with time.

We should use `tracemalloc` and other tools to see how we can fix this problem.

**Comment by hmcezar** [comment]
> Nice graph! sweat_smile Maybe try loading HDF5 1.21.0 if it's availble on Saga, so we can actually make sure it's a HDF5 issue?

Unfortunately, it's not available.. but I'll check if there's an easybuild for it :)

**Comment by Lun4m** [comment]
Maybe this [software](https://github.com/bloomberg/memray) might be useful?

**Comment by hmcezar** [comment]
One thing that is strange to me is how different, for the same input (and same number of MPI processes), is the memory usage on Saga:
![mprof_saga](https://user-images.githubusercontent.com/7842354/180185059-2b900682-deb1-44d5-8a65-5291558af055.png)

And on my laptop:
![mprof_local](https://user-images.githubusercontent.com/7842354/180185092-2f8d944c-697d-43b5-9dd9-653fb500d6da.png)

There are a few differences concerning MPI implementation (OpenMPI on Saga and MPICH on my laptop), Python versions etc.. but still the difference is huge.
However, it is still possible to notice a small leak even on my laptop.

**Comment by hmcezar** [comment]
This is the profiling of the main loop for about 2000 steps running on my machine using [Blackfire](https://blackfire.io):

https://blackfire.io/profiles/4b4e2cd8-6985-49a3-97d5-d6925326f515/graph

The memory profiling seems to point to `pmesh.domain.Layout._exchange` so maybe the problem is there?

**Comment by hmcezar** [comment]
Some more information. If I run HyMD on Saga with 4 MPI processes I get what I got before
![mprof_parallel](https://user-images.githubusercontent.com/7842354/180434028-a117f54c-120f-4ba1-9f4e-c8f3e084fa5b.png)

However, if I run without `mpirun`
![mprof_serial](https://user-images.githubusercontent.com/7842354/180434108-6de27dd4-4b8d-4be4-bb7a-0ab66f9d1d66.png)

If I run with `mpirun -n 1` it also doesn't leak
![mprof_serial_mpirun1](https://user-images.githubusercontent.com/7842354/180435582-7c47a484-31e0-4f52-9679-73226690e7b5.png)

**Comment by Lun4m** [comment]
Which makes sense since from the Blackfire report it seemed the problem was about an `mpi4py.Alltoallv` call. 
I was looking at the source code for `pmesh.domain.Layout._exchange`, and the only place where that happens is [here](https://github.com/rainwoodman/pmesh/blob/174b3976ba112421d933f4b1b13610e5ab64eb26/pmesh/domain.py#L195-L205):
```python
dt = MPI.BYTE.Create_contiguous(itemsize)
dt.Commit()
dtype = numpy.dtype((data.dtype, data.shape[1:]))
recvbuffer = numpy.empty(self.recvlength, dtype=dtype, order='C')
self.comm.Barrier()

# now fire
rt = self.comm.Alltoallv((buffer, (self.sendcounts, self.sendoffsets), dt), 
                    (recvbuffer, (self.recvcounts, self.recvoffsets), dt))
dt.Free()
self.comm.Barrier()
```
Maybe you don't need to assign the variable `rt` and instead you just call `mpi4py.Alltoallv`? Could it be that simple? 😅

**Comment by hmcezar** [comment]
That was the first thing I tried when I saw that call, but unfortunately removing the `rt` didn't help :cry:.

I'm trying a different OpenMPI version (I'm having to recompile some stuff) to see if that fixes the problem. There were some fixes in the OpenMPI 4.1.2 onwards concerning leaks.

**Comment by hmcezar** [comment]
More evidence points to this OpenMPI version as the culprit of the leak. Running `memray` (thanks @Lun4m!) with its flags and tracking every allocation (and after a [bugfix](https://github.com/bloomberg/memray/issues/163)) , we see that the memory usage of the `mpi4py` import (last python call) that goes down to a `PMPI_Init_thread` call from the 4.1.1 module.
![image](https://user-images.githubusercontent.com/7842354/180793476-15cd0d0f-11b4-439a-84e7-ff1a6d179eec.png)

The full flamegraph is in this .HTML
[memray-flamegraph-hymd.21000.zip](https://github.com/Cascella-Group-UiO/HyMD/files/9181844/memray-flamegraph-hymd.21000.zip)

I opened a ticket with the sigma2 people requesting a newer toolchain with a more recent OpenMPI.
Hopefully, using this new toolchain this leak will be gone.

**Comment by hmcezar** [comment]
Good news, the problem apparently was, indeed, with OpenMPI.
![mprof_fixed](https://user-images.githubusercontent.com/7842354/181302524-c6af3201-e5af-491a-af31-d4ee6b78cc21.png)

With the `2022a` toolchain on Saga (which uses OpenMPI 4.1.4), HDF 1.13.1, and Python 3.10.4, the problem seems to be solved (at least the bigger leak, there might be others).

These are the loaded modules:
```bash
  1) StdEnv                        (S)   8) libxml2/2.9.13-GCCcore-11.3.0         15) PMIx/4.1.2-GCCcore-11.3.0   22) ncurses/6.3-GCCcore-11.3.0
  2) GCCcore/11.3.0                      9) libpciaccess/0.16-GCCcore-11.3.0      16) UCC/1.0.0-GCCcore-11.3.0    23) libreadline/8.1.2-GCCcore-11.3.0
  3) zlib/1.2.12-GCCcore-11.3.0         10) hwloc/2.7.1-GCCcore-11.3.0            17) OpenMPI/4.1.4-GCC-11.3.0    24) Tcl/8.6.12-GCCcore-11.3.0
  4) binutils/2.38-GCCcore-11.3.0       11) OpenSSL/1.1                      (H)  18) gompi/2022a                 25) SQLite/3.38.3-GCCcore-11.3.0
  5) GCC/11.3.0                         12) libevent/2.1.12-GCCcore-11.3.0        19) Szip/2.1.1-GCCcore-11.3.0   26) GMP/6.2.1-GCCcore-11.3.0
  6) numactl/2.0.14-GCCcore-11.3.0      13) UCX/1.12.1-GCCcore-11.3.0             20) HDF5/1.13.1-gompi-2022a     27) libffi/3.4.2-GCCcore-11.3.0
  7) XZ/5.2.5-GCCcore-11.3.0            14) libfabric/1.15.1-GCCcore-11.3.0       21) bzip2/1.0.8-GCCcore-11.3.0  28) Python/3.10.4-GCCcore-11.3.0
```

And these are the packages in my Python environment:
```bash
Cython==0.29.30
h5py==3.7.0
-e git+https://github.com/hmcezar/HyMD.git@621c95abbc8f57f46f04fea12550111b7bda5c09#egg=hymd
memory-profiler==0.60.0
mpi4py==3.1.3
mpmath==1.2.1
mpsort==0.1.17
networkx==2.8.5
numpy==1.23.1
pfft-python==0.1.21
pmesh==0.1.56
psutil==5.9.1
sympy==1.10.1
tomli==2.0.1
```

**Comment by pablogsal** [comment]
👋 Hi @hmcezar,

I am one of the authors of `memray`. We are collecting success stories [here](https://github.com/bloomberg/memray/discussions/226). If you have a minute, do you mind leaving a short message on how `memray` helped with this issue? Knowing how we managed to help will help us track trends and target areas for improvement, prioritize new features and development and identify potential bugs or areas of confusion.

Thanks a lot for your consideration and for helping us improve the profiler :)
