### ISSUE TITLE
Add header to log file

### ISSUE THREAD

**Issue by hmcezar** [Cascella-Group-UiO/HyMD#190]
Not a very important issue, but currently, the log file does not have any indication that it is a HyMD log output.

This is important especially to have the version the user is running easily accessible (currently it is available in the .H5 only).
We could refactor the code we currently have into a function and call it to print the header
https://github.com/Cascella-Group-UiO/HyMD/blob/63c343de9abe22a3ee50c93b9ab6b90924f9c9d1/hymd/file_io.py#L171-L195

For fun and to create some identity, it would also be nice to add a header with a figlet of "Hylleraas MD" or "HyMD" like:
```
Testing font small
 _  _      _ _                        __  __ ___  
| || |_  _| | |___ _ _ __ _ __ _ ___ |  \/  |   \ 
| __ | || | | / -_) '_/ _` / _` (_-< | |\/| | |) |
|_||_|\_, |_|_\___|_| \__,_\__,_/__/ |_|  |_|___/ 
      |__/                          
```
```
Testing font ogre
              _ _                                      ___ 
  /\  /\_   _| | | ___ _ __ __ _  __ _ ___    /\/\    /   \
 / /_/ / | | | | |/ _ \ '__/ _` |/ _` / __|  /    \  / /\ /
/ __  /| |_| | | |  __/ | | (_| | (_| \__ \ / /\/\ \/ /_// 
\/ /_/  \__, |_|_|\___|_|  \__,_|\__,_|___/ \/    \/___,'  
        |___/                                              
```
```
Testing font slant
    __  __      ____                              __  _______ 
   / / / /_  __/ / /__  _________ _____ ______   /  |/  / __ \
  / /_/ / / / / / / _ \/ ___/ __ `/ __ `/ ___/  / /|_/ / / / /
 / __  / /_/ / / /  __/ /  / /_/ / /_/ (__  )  / /  / / /_/ / 
/_/ /_/\__, /_/_/\___/_/   \__,_/\__,_/____/  /_/  /_/_____/  
      /____/     
```

There are a lot of examples in the attached .txt (generated using [this gist](https://gist.github.com/Technetium1/f97474f52096303d556963d37f59edee)).
[test.txt](https://github.com/Cascella-Group-UiO/HyMD/files/9280217/test.txt)

What do you think? Any favorite banners? hahahah

**Comment by hmcezar** [comment]
I have implemented a suggestion of how the header could look like in [this branch](https://github.com/hmcezar/HyMD/tree/header).

![image](https://user-images.githubusercontent.com/7842354/183439455-e78ace3a-d5f5-4de5-9587-b196934794b9.png)

If `GitPython` is installed the "[header branch commit 28faea7]" is added based on branch and commit, otherwise the version is just the value in `__version__`.

**Comment by Lun4m** [comment]
Looks beautiful! 😮
