### ISSUE TITLE
JOSS Review - Additional community guidelines suggestions

### ISSUE THREAD

**Issue by blakeaw** [Cascella-Group-UiO/HyMD#207]
Hi, this issue is part of the JOSS Review at https://github.com/openjournals/joss-reviews/issues/4149. 

Regarding the community guidelines:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I see that this item was addressed in https://github.com/Cascella-Group-UiO/HyMD/pull/163 by adding guidelines in the repo's CONTRIBUTING.md. However, I have a couple of follow-up suggestions.

------
First, I'd suggest that you also link to the CONTRIBUTING.md in the docs. For example, a good place might be under https://cascella-group-uio.github.io/HyMD/index.html#development; you could add some text that notes you also welcome contributions from the broader community (including reporting issues/problems) and point folks to the CONTRIBUTING.md for the relevant guidelines. 

It might also be helpful to add a `## Contributing` section to the repo's README that points folks to the CONTRIBUTING.md.  

------
Second, regarding 
> 3) Seek support

Should users also use the repo's issue tracker to request support?  Or, are there other ways to seek support, such as via email or chat groups (Gitter, Discord, Slack, etc.)? 

I'd suggest clarifying this as well in the README and docs.

**Comment by samiransen23** [comment]
@blakeaw Thanks for this comment. We will look into it.

@Lun4m: It would be nice if you could take a look.

**Comment by samiransen23** [comment]
Hi @blakeaw !
Sorry for the late reply, and thanks for the suggestions.
We have now mentioned CONTRIBUTING.md in the documentation under section: development, as well as linking it in README.md of the repository.  
For seeking support, we prefer the issue tracker, which we have mentioned and linked now in the documentation as well as CONTRIBUTING.md.

The issue should be resolved with commit f9d789e.

**Comment by blakeaw** [comment]
Ok, great! Looks good. I'll go ahead and close this issue. I'll let the editor know in the review thread (https://github.com/openjournals/joss-reviews/issues/4149) you have addressed it. Thanks!
